<a href="https://colab.research.google.com/github/rohini6813/Start_Up-Data-Analysis-/blob/main/start_up_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

10 Nov

In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [42]:
df = pd.read_csv("/content/drive/MyDrive/R K Data Analytic/Colab Notebooks/Data Set/startup_funding (1).csv")
df

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN
...,...,...,...,...,...,...,...,...,...,...
3039,3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
3040,3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
3041,3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
3042,3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
3043,3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

In [43]:
#to delete the column
df.drop(columns = ['Remarks'], inplace = True)
df

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"
...,...,...,...,...,...,...,...,...,...
3039,3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000"
3040,3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000"
3041,3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000"
3042,3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN
3043,3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000"

In [44]:
#which col is present in the data set withe there datatype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   object
 2   Startup Name       3044 non-null   object
 3   Industry Vertical  2873 non-null   object
 4   SubVertical        2108 non-null   object
 5   City  Location     2864 non-null   object
 6   Investors Name     3020 non-null   object
 7   InvestmentnType    3040 non-null   object
 8   Amount in USD      2084 non-null   object
dtypes: int64(1), object(8)
memory usage: 214.2+ KB

In [45]:
#to remane the col name
df.rename(columns = {"Date dd/mm/yyyy":"Date",
                    "Startup Name": "Startup",
                     "SubVertical":"Subvertical",
                     "City  Location": "City",
                     "Amount in USD":"Amount"}, inplace = True)
df

,Sr No,Date,Startup,Industry Vertical,Subvertical,City,Investors Name,InvestmentnType,Amount
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"
...,...,...,...,...,...,...,...,...,...
3039,3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000"
3040,3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000"
3041,3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000"
3042,3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN
3043,3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000"

- in Amount column ',' in present hence it show as string, for that we have to replace the ',' with nothing('')
- also replace undisclosed with nothing('')

In [46]:
# if we perform the operation we have to specify witch col we have to modify in front of operation.
#col name   =  replace
df['Amount'] = df['Amount'].str.replace(',', '')

- Amount datatype is object we have to convert it into integer or float

In [47]:
#pd.numeric is used to convert the passed argument to a numeric type.
#errors = 'coerec'- convert problematic inputs to NaT (Not a Time).
df['Amount'] = pd.to_numeric(df['Amount'] ,errors='coerce')

In [48]:
df['Date']

0       09/01/2020
1       13/01/2020
2       09/01/2020
3       02/01/2020
4       02/01/2020
           ...
3039    29/01/2015
3040    29/01/2015
3041    30/01/2015
3042    30/01/2015
3043    31/01/2015
Name: Date, Length: 3044, dtype: object

In [49]:
#convert date formate
df['Date']= pd.to_datetime(df['Date'],errors ='coerce' ,format="%d/%m/%Y")
df

,Sr No,Date,Startup,Industry Vertical,Subvertical,City,Investors Name,InvestmentnType,Amount
0,1,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000.0
1,2,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394.0
2,3,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860.0
3,4,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000.0
4,5,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000.0
...,...,...,...,...,...,...,...,...,...
3039,3040,2015-01-29,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,4500000.0
3040,3041,2015-01-29,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,825000.0
3041,3042,2015-01-30,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,1500000.0
3042,3043,2015-01-30,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN
3043,3044,2015-01-31,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,140000.0

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date               3036 non-null   datetime64[ns]
 2   Startup            3044 non-null   object
 3   Industry Vertical  2873 non-null   object
 4   Subvertical        2108 non-null   object
 5   City               2864 non-null   object
 6   Investors Name     3020 non-null   object
 7   InvestmentnType    3040 non-null   object
 8   Amount             2065 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(6)
memory usage: 214.2+ KB

In [51]:
df.isnull().sum()

Sr No                  0
Date                   8
Startup                0
Industry Vertical    171
Subvertical          936
City                 180
Investors Name        24
InvestmentnType        4
Amount               979
dtype: int64

In [52]:
#to find the percentage
df.isnull().mean() * 100

Sr No                 0.000000
Date                  0.262812
Startup               0.000000
Industry Vertical     5.617608
Subvertical          30.749014
City                  5.913272
Investors Name        0.788436
InvestmentnType       0.131406
Amount               32.161629
dtype: float64

In [53]:
# fillna - replaces the NULL values with a specified value
df['Amount'] = df['Amount'].fillna(df['Amount'].mean())

In [54]:
df.head()

,Sr No,Date,Startup,Industry Vertical,Subvertical,City,Investors Name,InvestmentnType,Amount
0,1,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000.0
1,2,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394.0
2,3,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860.0
3,4,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000.0
4,5,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000.0

In [55]:
#avg of amount col
df['Amount'].mean()

18429897.27080872

In [56]:
df.isnull().mean() * 100

Sr No                 0.000000
Date                  0.262812
Startup               0.000000
Industry Vertical     5.617608
Subvertical          30.749014
City                  5.913272
Investors Name        0.788436
InvestmentnType       0.131406
Amount                0.000000
dtype: float64

In [57]:
#To calculate the mode of a group of numbers
df['Subvertical'].mode()

0    Online Lending Platform
Name: Subvertical, dtype: object

In [58]:
#Fill the missing values in subvertical column with unknown
df['Subvertical'] = df['Subvertical'].fillna('Unknown')

In [59]:
df['Year'] = df['Date'].dt.year

In [60]:
df.head()

,Sr No,Date,Startup,Industry Vertical,Subvertical,City,Investors Name,InvestmentnType,Amount,Year
0,1,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000.0,2020.0
1,2,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394.0,2020.0
2,3,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860.0,2020.0
3,4,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000.0,2020.0
4,5,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000.0,2020.0

In [61]:
#removes the rows that contains NULL values
df.dropna(subset=['Date','Industry Vertical','City','Investors Name','InvestmentnType'],inplace = True)
df

,Sr No,Date,Startup,Industry Vertical,Subvertical,City,Investors Name,InvestmentnType,Amount,Year
0,1,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,2.000000e+08,2020.0
1,2,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8.048394e+06,2020.0
2,3,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,1.835886e+07,2020.0
3,4,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3.000000e+06,2020.0
4,5,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1.800000e+06,2020.0
...,...,...,...,...,...,...,...,...,...,...
2868,2869,2015-04-29,Tracxn,Startup Analytics platform,Unknown,Bangalore,SAIF Partners,Private Equity,3.500000e+06,2015.0
2869,2870,2015-04-29,Dazo,Mobile Food Ordering app,Unknown,Bangalore,"Sumit Jain, Aprameya Radhakrishna, Alok Goel, ...",Seed Funding,1.842990e+07,2015.0
2870,2871,2015-04-29,Tradelab,Financial Markets Software,Unknown,Bangalore,Rainmatter,Seed Funding,4.000000e+05,2015.0
2871,2872,2015-04-29,PiQube,Hiring Analytics platform,Unknown,Chennai,The HR Fund,Seed Funding,5.000000e+05,2015.0
2872,2873,2015-04-29,Travel Triangle,Online Travel Marketplace,Unknown,Noida,"Bessemer Venture Partners, SAIF Partners",Private Equity,8.000000e+06,2015.0

In [62]:
#find the start up in which Ratan tata invested
df[df['Investors Name'] == 'Ratan Tata']

,Sr No,Date,Startup,Industry Vertical,Subvertical,City,Investors Name,InvestmentnType,Amount,Year
347,348,2018-03-27,The Print,Media,News portal,Delhi,Ratan Tata,Seed / Angel Funding,5.350000e+05,2018.0
1266,1267,2016-10-04,GOQii,Consumer Internet,Health & Fitness Wearable Device,Mumbai,Ratan Tata,Private Equity,1.842990e+07,2016.0
1367,1368,2016-09-13,IdeaChakki,Consumer Internet,Restaurant Menu & Food mobile app,Delhi,Ratan Tata,Seed Funding,1.842990e+07,2016.0
1590,1591,2016-06-10,Kyazoonga,eCommerce,Online event ticketing Platform,Mumbai,Ratan Tata,Seed Funding,1.842990e+07,2016.0
1717,1718,2016-05-19,Niki.ai,Technology,Artificial Intelligence Platform,Bangalore,Ratan Tata,Private Equity,1.842990e+07,2016.0
1788,1789,2016-04-19,LensKart,eCommerce,Eyewear etailing platform,New Delhi,Ratan Tata,Private Equity,1.842990e+07,2016.0
1926,1927,2016-02-08,Moglix,Ecommerce,Industrial & Home Products Marketplace,New Delhi,Ratan Tata,Private Equity,1.842990e+07,2016.0
1933,1934,2016-02-08,Invictus Oncology,Healthcare,Cancer therapeutic Info & Solutions,New Delhi,Ratan Tata,Private Equity,1.842990e+07,2016.0
1952,1953,2016-02-15,Snapbizz,Technology,Connectivity platform for local grocery stores,Bangalore,Ratan Tata,Private Equity,1.842990e+07,2016.0
1968,1969,2016-02-17,Bollant Industries,Technology,Eco-friendly consumer & packaging products,Hyderabad,Ratan Tata,Private Equity,1.842990e+07,2016.0
2001,2002,2016-02-29,Nestaway,Consumer Internet,Online Home Rental Marketplace,Bangalore,Ratan Tata,Private Equity,1.842990e+07,2016.0
2006,2007,2016-01-04,DogSpot,ECommerce,Online Pet Store,Gurgaon,Ratan Tata,Seed Funding,1.842990e+07,2016.0
2014,2015,2016-01-06,Tracxn,BFSI,Startup Funding Deal Discovery & Execution pla...,Bangalore,Ratan Tata,Seed Funding,1.842990e+07,2016.0
2060,2061,2016-01-19,Cashkaro,Consumer Internet,Coupon & Cashback platform,Gurgaon,Ratan Tata,Private Equity,1.842990e+07,2016.0
2072,2073,2016-01-21,FirstCry,ECommerce,Kids Focused eTailer,Pune,Ratan Tata,Private Equity,1.842990e+07,2016.0
2089,2090,2016-01-27,Teabox.com,ECommerce,Specialty Tea ETailer,Siliguri,Ratan Tata,Private Equity,1.842990e+07,2016.0
2151,2152,2015-12-11,UrbanClap,Hyperlocal On-Demand Household Services platform,Unknown,Gurgaon,Ratan Tata,Private Equity,1.842990e+07,2015.0
2200,2201,2015-11-03,Sabse,WiFi \xe2\x80\x93 first Cloud communication pl...,Unknown,Mumbai,Ratan Tata,Private Equity,1.842990e+07,2015.0
2268,2269,2015-11-24,Crayon Data,Big Data Analytics Platform,Unknown,Chennai/ Singapore,Ratan Tata,Private Equity,1.842990e+07,2015.0
2386,2387,2015-09-02,HolaChef,Food Delivery Platform,Unknown,Mumbai,Ratan Tata,Private Equity,1.842990e+07,2015.0
2573,2574,2015-07-01,Ola Cabs,Cab rental Mobile app,Unknown,Bangalore,Ratan Tata,Private Equity,1.842990e+07,2015.0
2596,2597,2015-07-08,Ampere,Electric Scooter manufacturer,Unknown,Coimbatore,Ratan Tata,Seed Funding,1.842990e+07,2015.0
2685,2686,2015-06-03,KAARYAH,Women Lifestyle Marketplace,Unknown,Gurgaon,Ratan Tata,Seed Funding,1.842990e+07,2015.0

In [63]:
df[df['Investors Name'] == 'Ratan Tata'].head(5)

,Sr No,Date,Startup,Industry Vertical,Subvertical,City,Investors Name,InvestmentnType,Amount,Year
347,348,2018-03-27,The Print,Media,News portal,Delhi,Ratan Tata,Seed / Angel Funding,5.350000e+05,2018.0
1266,1267,2016-10-04,GOQii,Consumer Internet,Health & Fitness Wearable Device,Mumbai,Ratan Tata,Private Equity,1.842990e+07,2016.0
1367,1368,2016-09-13,IdeaChakki,Consumer Internet,Restaurant Menu & Food mobile app,Delhi,Ratan Tata,Seed Funding,1.842990e+07,2016.0
1590,1591,2016-06-10,Kyazoonga,eCommerce,Online event ticketing Platform,Mumbai,Ratan Tata,Seed Funding,1.842990e+07,2016.0
1717,1718,2016-05-19,Niki.ai,Technology,Artificial Intelligence Platform,Bangalore,Ratan Tata,Private Equity,1.842990e+07,2016.0

In [64]:
#1. How has the total funding amount changed over the years?
df.groupby('Amount')['Year'].sum()

Amount
1.800000e+04    2017.0
2.000000e+04    2015.0
2.250000e+04    8065.0
2.500000e+04    2016.0
2.700000e+04    2016.0
                 ...
7.000000e+08    2015.0
1.000000e+09    2019.0
1.400000e+09    4034.0
2.500000e+09    2017.0
3.900000e+09    2019.0
Name: Year, Length: 433, dtype: float64

In [65]:
#2. Which are the top 5 most-funded startups?
df.groupby('Startup')['Amount'].sum().sort_values(ascending=False).head(5)

Startup
Flipkart            4.059700e+09
Rapido Bike Taxi    3.900000e+09
Paytm               3.148950e+09
Ola                 9.845000e+08
Udaan               8.700000e+08
Name: Amount, dtype: float64

In [66]:
#3. Which sub-sectors receive the highest funding?
df.groupby('Subvertical')['Amount'].sum().sort_values(ascending=False)

Subvertical
Unknown                               1.183675e+10
Bike Taxi                             3.900000e+09
Online Marketplace                    2.648700e+09
ECommerce Marketplace                 1.700000e+09
Mobile Wallet & ECommerce platform    1.460000e+09
                                          ...
Audio Technology Solutions            2.250000e+04
Mobile Email productivity tool        2.250000e+04
Augmented Reality Solutions           2.250000e+04
Cloud based Virtual Servers           2.250000e+04
Smart Online address tags             1.800000e+04
Name: Amount, Length: 1919, dtype: float64

In [67]:
#4. Which investors have repeatedly funded specific startups, and how frequently?
fund = df.groupby(['Investors Name', 'Startup']).size().reset_index(name='Funding Count')
fund[fund['Funding Count'] > 1]

,Investors Name,Startup,Funding Count
357,Bertelsmann India Investments,Roposo,2
716,Flipkart,TinyStep,2
1051,Info Edge (India) Ltd,BigStylist,2
1052,Info Edge (India) Ltd,Canvera,2
1277,L\\xe2\\x80\\x99Occitane,MyGlamm,2
1394,March Capital Partners,Uniphore,2
1470,"Mohammed Khan, Sameer Narayan & Others",Fincash,2
1576,Nexus Venture Partners,Postman,2
2273,"Sunil Munjal, Harsh Mariwala, Dalip Pathak and...",Nykaa,2
2358,Tiger Global Management,Chaayos,2
2689,Warburg Pincus,Ecom Express,2
2817,vCommission,LetReach,2

In [68]:
#5. What is the total funding amount for each city where "IDG Ventures" was an investor?
inv =  df[df['Investors Name'].str.contains("IDG Ventures", na=False)]
inv.groupby(['City', 'Investors Name'])['Amount'].sum().reset_index(name='Total Amount')

         City                                     Investors Name  Total Amount
0   Bangalore                 Accel Partners, IDG Ventures India  5.000000e+06
1   Bangalore  Accel Partners, IDG Ventures, Endiya Partners,...  5.800000e+06
2   Bangalore      Accel Partners, IDG Ventures, Kalaari Capital  1.500000e+07
3   Bangalore  Accel Partners, IDG Ventures, Kalaari Capital,...  2.500000e+07
4   Bangalore                                 IDG Ventures India  1.942990e+07
5   Bangalore  IDG Ventures India, Inventus Capital, Blume Ve...  6.000000e+06
6   Bangalore  IDG Ventures India, Michael & Susan Dell Found...  3.650000e+06
7   Bangalore  IDG Ventures India,\\xc2\\xa0 Accel Partners I...  2.000000e+06
8   Bangalore                      IDG Ventures, Endiya Partners  1.350000e+06
9   Bangalore                  IDG Ventures, IDFC-Parampara Fund  1.842990e+07
10  Bangalore                      IDG Ventures, Sequoia Capital  1.500000e+07
11  Bangalore                  SAIF Partners, IDG Ventures India  4.000000e+06
12  Bengaluru  IDG Ventures, Accel Partners, Kalaari Capital ...  1.200000e+08
13    Chennai                                       IDG Ventures  9.100000e+06
14    Chennai  IDG Ventures India, Elevar Equity, Accion Vent...  2.500000e+06
15    Chennai  IDG Ventures, Indian Angel Network (IAN), Your...  2.000000e+06
16    Chennai                  IDG Ventures, Kris Gopalakrishnan  1.842990e+07
17    Chennai             The Chennai Angels, IDG Ventures India  1.000000e+06
18    Chennai      Vertex Ventures, Cisco Ventures, IDG Ventures  6.000000e+06
19      Delhi  Neoplux, OPPO, IDG Ventures India, Kalaari Cap...  5.500000e+06
20    Gurgaon  IDG Ventures, M & S partners, Powerhouse Ventu...  1.000000e+06
21     Mumbai  Aspada Advisors, IDG Ventures,\\xc2\\xa0 Inven...  5.000000e+06
22     Mumbai  B Capital, International Finance Corporation (...  2.200000e+07
23     Mumbai                                       IDG Ventures  7.500000e+05
24     Mumbai                                 IDG Ventures India  1.842990e+07
25     Mumbai  IDG Ventures India, Omidyar Network, Sherpalo ...  2.000000e+06
26     Mumbai                       IDG Ventures, Accel Partners  3.000000e+06
27     Mumbai                      IDG Ventures, Axilor Ventures  6.000000e+05
28     Mumbai           IDG Ventures, Blume Ventures, Saha Fund,  1.350000e+06
29     Mumbai       IDG Ventures, Sequoia Capital, GREE Ventures  5.300000e+06
30     Mumbai                       Notion Capital, IDG Ventures  2.700000e+06
31  New Delhi  500 Startups, IDG Ventures & Advantedge fund, ...  1.842990e+07
32  New Delhi  Blume Ventures, IDG Ventures & Indian Angel Ne...  1.000000e+06
33  New Delhi  GREE Ventures, Kalaari Capital and IDG Venture...  3.100000e+06
34  New Delhi  IDG Ventures India, Kalaari Capital, 500 Startups  2.000000e+06
35  New Delhi  IDG Ventures, Inventus Capital, Indian Angel N...  1.842990e+07
36  New Delhi  International Finance Corp, TPG Growth, Adveq ...  6.000000e+07
37  New Delhi  Orchid India, Hornbill Orchid India Fund, Chir...  3.591375e+06
38       Pune                                       IDG Ventures  4.000000e+06
39       Pune       IDG Ventures India Advisors, Jungle Ventures  4.000000e+06
40       Pune  SAIF Partners, IDG Ventures India, Vertex Vent...  1.250000e+07
41       Pune  Silicon Valley Ventures, NEA Ventures, Valiant...  1.000000e+07
42  Singapore                Kalaari Capital, IDG Ventures India  3.000000e+06

In [69]:
#6. What is the amount spent by the investor in each startup?
df.groupby(['Investors Name', 'Startup'])['Amount'].sum()

Investors Name                          Startup
"Kedaraa Capital, Ontario Teachers\\'"  Spandana Sphoorty    19500000.0
021 Capita, Binny Bansal                Increff               3000000.0
1Crowd                                  Fourth Ambit           600000.0
                                        Nuvepro                400000.0
1Crowd (through crowd funding)          Zipgrid                200000.0
                                                                ...
undisclosed investors                   Sumeru                1000000.0
                                        ZippServe              390000.0
undisclosed private investors           Flexing It             500000.0
vCommission                             Hoppingo                89000.0
                                        LetReach               200000.0
Name: Amount, Length: 2818, dtype: float64

In [70]:
#7. Who are the top investors in the FinTech sector, and how much have they invested?
fintech_investments = df[df['Industry Vertical'] == 'FinTech']
top_investors_fintech = fintech_investments.groupby(['Investors Name'])['Amount'].sum().sort_values(ascending=False)
top_investors_fintech

Investors Name
Vijay Shekhar Sharma                    1.000000e+09
RPS Ventures                            1.100000e+08
WestBridge Capital                      5.200000e+07
Tiger Global Management                 3.050000e+07
FinTech                                 1.741126e+07
Matrix Partners India, Sequoia India    4.500000e+06
SAIF Partners                           3.300000e+06
Vinod Khatumal                          3.000000e+06
Name: Amount, dtype: float64

In [71]:
#8. What is the average funding amount?
df['Amount'].mean()

18738259.295067023

In [72]:
df.head(1)

,Sr No,Date,Startup,Industry Vertical,Subvertical,City,Investors Name,InvestmentnType,Amount,Year
0,1,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000.0,2020.0

In [73]:
# 1. Funding Over Time
funding_by_year = df.groupby('Year')['Amount'].sum().reset_index()
fig1 = px.line(funding_by_year, x='Year', y='Amount', title='Total Funding Over the Years',
               labels={'Amount': 'Total Funding (INR)', 'Year': 'Year'})
fig1.show()

In [74]:
# 2. Top Startups by Funding
top_startups = df.groupby('Startup')['Amount'].sum().reset_index().sort_values(by='Amount', ascending=False).head(10)
fig2 = px.bar(top_startups, x='Startup', y='Amount', title='Top 10 Funded Startups',
              labels={'Amount': 'Total Funding (INR)', 'Startup': 'Startup'})
fig2.show()

In [75]:
# 3. Funding Distribution by Industry
industry_funding = df.groupby('Industry Vertical')['Amount'].sum().reset_index().sort_values(by='Amount', ascending=False).head(10)
fig3 = px.pie(industry_funding, names='Industry Vertical', values='Amount', title='Funding Distribution by Industry')
fig3.show()

In [76]:
# 4. Funding by City
city_funding = df.groupby('City')['Amount'].sum().reset_index().sort_values(by='Amount', ascending=False).head(10)
fig4 = px.bar(city_funding, x='City', y='Amount', title='Top 10 Cities by Funding',
              labels={'Amount': 'Total Funding (INR)', 'City': 'City'})
fig4.show()